publishDir = "../docs"
baseURL = "https://aws-cli-eq-pwsh.shibata.tech/"
relativeURLs = true
languageCode = "en-us"
title = "AWS CLI -eq PowerShell"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-47904214-2"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "This is the lists of AWS PowerShell Cmdlets equivalent with AWS CLI commands."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

[menu]
  [[menu.nav]]
    name = "GitHub"
    url = "https://github.com/stknohg/aws-cli-eq-pwsh/"
    weight = 1
  [[menu.nav]]
    name = "Twitter"
    url = "https://twitter.com/stknohg"
    weight = 2
  [[menu.nav]]
    name = "Theme"
    url = "https://themes.gohugo.io/papercss-hugo-theme/"
    weight = 3
